name: Nicotine+ CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        python: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        sudo apt-get install libgeoip-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # warn if there are Python syntax errors or undefined names. exit-zero treats all errors as warnings
        flake8 pynicotine --count --exit-zero --max-complexity=10 --statistics
      continue-on-error: true
    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        pip install pytest
        pytest
      continue-on-error: true
